### ISSUE TITLE
Setting up on heroku

### ISSUE THREAD

**Issue by realjax** [andrei-tatar/nora-service#21]
I'm stuck at setting up on heroku.

I got it all deployed at heroku bu cant login to the app, it says 
![Screenshot 2020-04-28 at 12 11 09](https://user-images.githubusercontent.com/883435/80475733-9db93500-8949-11ea-8d6f-5f599bd3a91c.png)

I added it to firebase of course as per the instructions,

![Screenshot 2020-04-28 at 13 23 10](https://user-images.githubusercontent.com/883435/80481904-9c8d0580-8953-11ea-9fe0-d151e673555c.png)

 but it still doesnt work.  Any idea's ?

**Comment by realjax** [comment]
Not sure what is going on but it seems to think it is not in production mode.
the init.js from heroku still says this:

```
"apiKey": "xxx",
  "authDomain": "node-red-home-automation-82192.firebaseapp.com",
  "databaseURL": "https://node-red-home-automation-82192.firebaseio.com",
  "projectId": "node-red-home-automation-82192",
  "storageBucket": "node-red-home-automation-82192.appspot.com",
  "messagingSenderId": "350438145283",
  "remoteInitUrl": "/login/init.js",
  "jsBaseUrl": "https://www.gstatic.com/firebasejs/5.6.0"
```

which are all default settings it seems..

**Comment by realjax** [comment]
The logs on Heroku also say this:

 Warning, FIREBASE_CONFIG and GCLOUD_PROJECT environment variables are missing

**Comment by realjax** [comment]
Im going to close this,  this is costing me too much time.

**Comment by nicandris** [comment]
hey thanx for the comments. i will fix asap. can you try this?

https://github.com/andrei-tatar/nora-service/pull/20/files

during my testing i found out you also need FIREBASE_APIKEY and FIREBASE_AUTHDOMAIN but Andrei says its not needed

**Comment by andrei-tatar** [comment]
When you create the actions project, google automatically creates a firebase project. If you use that one, it's not needed. It's how NORA is currently deployed.

Notice the same project id in the url in actions console and firebase console.

![image](https://user-images.githubusercontent.com/6473183/80807021-c39e3e00-8bc4-11ea-8854-6c27ceb40b61.png)

![image](https://user-images.githubusercontent.com/6473183/80807053-d749a480-8bc4-11ea-84a8-da70673da078.png)
