### ISSUE TITLE
Themostat command "make it cooler" returns "setpoint: [object object]-1.5"

### ISSUE THREAD

**Issue by gittyhubbyfrankybobby** [andrei-tatar/nora-service#22]
If I tell my google home to "make it cooler in <thermostat location>" I get a node-red message with msg.payload.setpoint: "[object Object]-1.5"

![image](https://user-images.githubusercontent.com/15616257/82232308-79bf9280-98fc-11ea-8617-b790a4e63631.png)

setting  a specific temp works just fine.

Thanks for building this,  I just sent you a few dollars.

**Comment by andrei-tatar** [comment]
Just pushed a fix to the service. Should work now.

**Comment by gittyhubbyfrankybobby** [comment]
Looks great! thanks!
