### ISSUE TITLE
Continuing to develop going forward?

### ISSUE THREAD

**Issue by rgerrans** [andrei-tatar/nora-service#36]
@andrei-tatar I noticed you've been quiet in the forums and didn't move forward with the code refactoring to run local . I was thinking about adding sensors to the devices now that Imperihome shutdown) but didn't want to spend the time if you weren't still working on this / available to push code updates?

If it's reached end of life, I don't know if there is an easy way to give a few of us access to the backend to push in nora-service updates so we can keep the great work you did moving forward (would need to be someone more technical than me ;-).

Thanks,

Ron

**Comment by andrei-tatar** [comment]
@rgerrans I don't think it's reached the end of life, I do use it daily in my home. It's more important to me to keep it stable.
But indeed, I don't have the time now to continue working on this/push code updates.

I can grant you access to heroku/git and trust you will continue with the improvements if you have the time.

**Comment by rgerrans** [comment]
@andrei-tatar Sounds good. I'll reach out in the forum to try to get someone with more technical chops than I have. As I'm sure you noticed, my programming days are long behind me so it's more of code modification w/ only 80-90% understanding of what I did so would like to have another partner involved who can put good qa eyes on anything I do.

Definitely will help moving things forward. Thanks

**Comment by rgerrans** [comment]
@andrei-tatar Finally got back to this and just posted. Thanks again for all the work getting this going.
