### ISSUE TITLE
Help with Google API console

### ISSUE THREAD

**Issue by artomka** [andrei-tatar/nora-service#38]
Hi, I am trying to make the NORA-Service work on my server and I am going through the short tutorial from the main page. However, in the Google API console section, it is explained too short. I cannot get through it. Could you describe this part more precisely? Thank you.

**Comment by artomka** [comment]
solved by myself :)

**Comment by jerom87** [comment]
hi @artomka could you explain what you did or rather what the problem was?
You don´t have any problem to connect Google Home to your account like here #35 ?

**Comment by Raul-7-7** [comment]
I would love to know as well @artomka . Once I get this setup, I will put together a detail walkthrough. However, I cant make it work for myself. Would you mind sharing. 
I have asked @andrei-tatar for some clarity as well.
