### ISSUE TITLE
Lock Updates

### ISSUE THREAD

**Issue by rgerrans** [andrei-tatar/nora-service#7]
@andrei-tatar When you get a chance can you look at the pull request for the lock updates and let me know if I got everything in this time. Once you get a chance to update the Services, I'll test the new lock node.

Thanks.

**Comment by andrei-tatar** [comment]
@rgerrans I was now looking over the PR. What code editor are you using. Please use spaces, not tabs. As a suggestion, I'm using VS Code. Not sure if you like it, but it should make life easier.

Added some review comments:
https://github.com/andrei-tatar/nora-service/pull/6#pullrequestreview-314910946

**Comment by rgerrans** [comment]
@andrei-tatar I use Notepad+ I'm sure it has the option for saving with spaces instead of tabs when it auto-aligns so will get that fixed.

Thanks for the other feedback. Rookie mistake not thinking to do a test npm build on the backend. Still trying to build a mental map of how all the pieces flow. I'll take another run at it.

**Comment by andrei-tatar** [comment]
Merged https://github.com/andrei-tatar/nora-service/pull/9
